# Use postgres/example user/password credentials

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 54321:54321
    volumes:
      - pg_data:/var/lib/postgresql
      - ./db/:/docker-entrypoint-db
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: root
      POSTGRES_DB: main

volumes:
  pg_data:
    name: "freelance_architecture_backend"
